apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
      - image: diegolobo7/conversor-temperatura:latest
        name: conversor        
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: conversor
spec:
  selector: 
    app: conversor
  ports:
    - port: 80
      protocol: TCP
  type: NodePort